export { default as Header } from "./header"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as Imaged } from "./image"
export { default as Jumbo } from "./Jumbo"
export { default as Products } from "./Product"
export { default as ProductDetail } from "./ProductDetail"
export { default as Stars } from "./Stars"
